### ISSUE TITLE
Support for Google Dynamic Rendering

### ISSUE THREAD

**Issue by jorngeorg** [netlify/prerender#11]
The escaped fragment method used by this prerendering function has been [deprecated](https://developers.google.com/search/docs/ajax-crawling/docs/specification) by Google some time ago. And recently Google announced their new guideline method for prerendering, called [Dynamic Rendering ](https://youtu.be/PFwUbgvpdaQ?t=22m27s), and some new tools to go along with it; [Puppeteer](https://github.com/GoogleChrome/puppeteer) and [Rendrotron](https://github.com/GoogleChrome/rendertron).

I am wondering, as it not very well documented, if Netlify's prerendering service will support this new development? And/or if there is some kind of roadmap for the service, so that we can evaluate the long term use of it. Thanks!

**Comment by sinameraji** [comment]
are there any updates on this?

**Comment by bcomnes** [comment]
Not at the moment sorry.
