### ISSUE TITLE
Failed to register a ServiceWorker

### ISSUE THREAD

**Issue by kontrollanten** [netlify/prerender#17]
I get a lot of bugs in Sentry containing the following.

> SecurityError: Failed to register a ServiceWorker: No URL is associated with the caller's document.

Is it possible to disable service workers in Chrome from the CLI?

**Comment by bcomnes** [comment]
I don't think its possible to disable service workers.  Probably the easiest thing to do right now is to treat your codebase as a multi-environment/universal runtime target and handle the different failure modes.  

If there IS something we can do, I'm open to it, but this is a typical challenge when using SSR.

**Comment by bcomnes** [comment]
There may be a way to better handle rendering environments to accommodate service workers though.  It will require some research.

**Comment by kontrollanten** [comment]
As I understand it's possible to disable SW by disabling cookies in the browser. I'll see if I get time to do a PR for that.

**Comment by bcomnes** [comment]
Cool! That would be great :) I don't have the bandwidth at the moment to research that.
