### ISSUE TITLE
Doctype tag injected as string in content

### ISSUE THREAD

**Issue by jorngeorg** [netlify/prerender#20]
Hi,

I'm experiencing an issue where the `<!DOCTYPE html>` element is misinterpreted by the prerenderering engine and turned into a rouge string simply saying `html` and injected into the beginning of the html document. 

Anyone knows what is causing this? 

For example `http://localhost:3000/https://www.netlify.com`

yields

```
html<html lang="en"><head>
<meta name="generator" content="Hugo 0.36.1">
<meta charset="utf-8">
...
```

When testing with my own sites locally everything is fine if I remove the `<!DOCTYPE html>` declaration in my html file.

The rouge string makes the html of my page malformed so that the Facebook crawler is tripped up, which is the reason I'm using prerendering in the first place.

**Comment by jorngeorg** [comment]
They seem to have a fix for this here: https://github.com/prerender/prerender/issues/563

**Comment by fool** [comment]
Thanks @jorngeorg - we just came to the same conclusion in Netlify's helpdesk and came here to file a bug and found yours.  We'll try to get a fix live as soon as we can, but that won't be today as we are between maintainers on our service and it is (and has been for a long time) marked as beta quality, so the best fix will be to use your own prerender.io or prerender.cloud account for the immediate future.  ping us in the helpdesk if you get an API token you'd like us to put in place on your site or sites.

**Comment by fool** [comment]
(or, as you mentioned, you can remove the doctype tag)

**Comment by fool** [comment]
also observed by https://app.intercom.io/a/apps/q245f50x/inbox/inbox/search/conversations/21813067794 and a thread in community here:  https://community.netlify.com/t/prerendering-issue/672/2

**Comment by nirmalraghavan** [comment]
I'm also having this same issue. `<!DOCTYPE html>` causing issue with Facebook crawling. @fool : Is there any estimated time to get this fixed?

**Comment by fool** [comment]
No.  I'd recommend the work around suggested in this thread.

**Comment by pedsmoreira** [comment]
**The issue**
Removing <!DOCTYPE html> causes the page to be interpreted in Quirks Mode, and although this doesn't affect Prerendering very much, it can cause some weird visual side effects for users.

**Observations**
Among the most popular social medias that use OpenGraph tags for previewing, Facebook seems to be the only one that has an issue with this - it detects title and description, but skips the og:image.

**The workaround**
When no `og:image` is identified by Facebook, it looks for <img> tags in the page, defaulting to the first one it finds. You can use this in your favor by adding the same image that's inside `og:image` at the  beginning of the `<body>` section, with the `width` and `height` properties, as well as `display: none` to prevent users from seeing it.

**Comment by entozoon** [comment]
This should be higher priority, and a timeline given for Netlify's update of prerender if possible as it does appear to be fixed on their end.

The bug unexpectedly breaks the entire `<head>` parsing from the Facebook crawler's POV, and the proposed workarounds aren't great. Fighting quirks mode is a fate worse than death and hiding images at the start of body isn't necessarily feasible in a componentised app structure.

**Comment by jdcookie** [comment]
> This should be higher priority, and a timeline given for Netlify's update of prerender if possible as it does appear to be fixed on their end.
> 
> The bug unexpectedly breaks the entire `<head>` parsing from the Facebook crawler's POV, and the proposed workarounds aren't great. Fighting quirks mode is a fate worse than death and hiding images at the start of body isn't necessarily feasible in a componentised app structure.

Agree with this. Have tried using the workaround of dropping the Doctype, quirks mode just breaks the entire site. It's not a viable option for us to dedicate so much time to changing styling, which might fix things in one browser and break them in the next.

It would be really appreciated if this could get some attention as soon as possible.

**Comment by poziminski** [comment]
It seems like when "html" string is present, my browser (chrome) is automatically closing HEAD immediately and all the meta tags doesn't appear in head section. That's why facebook crawler is missing all tags.

**Really waiting for this issue to be fixed. It breaks the whole facebook sharing which is crucial for most sites, mine too.**

**Comment by jorngeorg** [comment]
@fool Any development on this? As @entozoon mentions, the workarounds proposed here doesn't really work. If we knew this would take forever to fix, we might have found other options. For me the prerendering for crawlers is a key reason for why I chose Netlify, and if that's not thing anymore I would have to move elsewhere.

**Comment by fool** [comment]
Sorry, but we don't have any ETA on a fix to change the behavior here,
Jørn.  This feature has been marked as "in beta" in our UI and docs for a
long time and continues to be in this status.  You can use your own account
different service like prerender.io or prerender.cloud if you have a paid
account with us.

**Comment by poziminski** [comment]
Don't want to be rude, but it seems like its just a matter of upgrading your `chrome-prerender` fork with origin `prerender`. 

You can read in `prerender` changelog:

> 5.5.1 - 2019-02-06
> Changed
> We were relying on document.doctype to return the full doctype string but that string changed in Chrome v72. We now parse the full doctype object directly in order to build the proper doctype and this change is backwards compatible with older Chrome versions.

Isn't it this part of code?
https://github.com/prerender/prerender/commit/3eaa5fb6ef5a7ef5242d7b480b6dfd83602b6dc0

**Comment by jorngeorg** [comment]
@fool Sure, I understand it's beta, and I wouldn't expect it to be first priority. But this has currently been broken for one and half month, and I have pointed you towards the fix, which from the outside looks pretty trivial. Many has built their sites around a feature that now is completely useless. 

You should at least make a big fat disclaimer in your docs and dashboard that this is currently broken and that there is no fix on the horizon, so that others do not get in to the same predicament.

**Comment by entozoon** [comment]
Thank you @biilmann / @rybit, very much appreciated!

**Comment by jorngeorg** [comment]
Brilliant! Thank you!
