### ISSUE TITLE
Merge conflics in README.md

### ISSUE THREAD

**Issue by dcshiller** [netlify/prerender#22]
The git merge conflict issues in the README.md make it difficult to follow.

**Comment by Glavin001** [comment]
Looks like the corrupted was introduced by @biilmann in https://github.com/netlify/prerender/commit/363ff892b8d0503698d604250c5a0e8a9089a40c#diff-04c6e90faac2675aa89e2176d2eec7d8

This is the previously committed README you can use as a temporary workaround: https://github.com/netlify/prerender/blob/33e3f6762b02bf1799903a941695e9e57288581b/README.md

**Comment by fool** [comment]
seems this got fixed awhile ago
