### ISSUE TITLE
Pages with dots get absolutely no metadata in Facebook Sharing Debugger

### ISSUE THREAD

**Issue by fabiofcferreira** [netlify/prerender#24]
Hey guys!

First of all, thanks for all this good work and everything you've done for me and for @upframe x) (Never forget that time, someone tried to SQL inject our Netlify Forms' Form).
We're using `react-helmet` and your pre-render feature (which I know is still in Beta). I'm reporting this issue for any other fellow programmers and users of pre-render can come here and know more.

I have one link (https://connect.upframe.io/hugo.franca) which has the metadata set, but somehow Facebook cannot fetch it. It fetches the root `/` metadata. Do you know what might be causing this problem?
I believe this is either a bug with Facebook or Netlify's pre-render and I also think that the fact that the path has a dot is also interfering as I created a new link (with the same data - without a dot in the URL) and it works. Here it is (https://connect.upframe.io/hugotest).

Thanks in advance for the great work

**Comment by fool** [comment]
cf https://netlify.zendesk.com/agent/tickets/9319 as well

**Comment by fool** [comment]
heya @fabiofcferreira - good research!  It affects not just facebook but all prerendering requests and is probably on our side.  We'll follow up here when we can get a fix.

**Comment by overlordofmu** [comment]
**Follow-ups**

https://answers.netlify.com/t/pre-rendering-not-working-with-certain-urls/36309

**Comment by fool** [comment]
FYI, we believe we fixed this several months ago.  Please reopen if you are still seeing this behavior after you have redeployed since 5 Oct.
