### ISSUE TITLE
URLs decoded too early

### ISSUE THREAD

**Issue by Pieparker** [netlify/prerender#34]
[Customer reported the following](https://netlify.zendesk.com/agent/tickets/46859):

> I just noticed that the URLs are decoded by the prerendering service before it's sent to the web app.
> 
> Check this sample repo: https://github.com/johanarnor/prerender-query-issue and its deploy on Netlify https://unruffled-bassi-05c528.netlify.app/
> 
> Visit e.g the following url (https://unruffled-bassi-05c528.netlify.app/?brand=H%26M&size=S) and see how window.location.search differs. Without prerendering the encoding is preserved, but with prerendering the URL seems to be corrupted by an extra decoding - %26 is decoded to &, which breaks the URL.
> 
> Switch user agents in chrome in order to trigger the prerender service https://developers.google.com/web/tools/chrome-devtools/device-mode/override-user-agent
> 
> I think it has been like this for a very long time (several years), we've just not noticed it until now.
> 
> If I remove the decoding on the following lines the url works just fine (locally at least).
> - https://github.com/netlify/prerender/blob/3f857de65394f9e1313d42e78e804042c6451c83/lib/util.js#L67
> - https://github.com/netlify/prerender/blob/3f857de65394f9e1313d42e78e804042c6451c83/lib/util.js#L100

Fool could repro using cURL:

```

% curl -v "https://unruffled-bassi-05c528.netlify.app/?brand=H%26M&size=S" 2>&1 | grep brand
GET /?brand=H%26M&size=S HTTP/1.1
  <p>Use e.g. the following query parameters: "?brand=H%26M&size=M"</p>
% curl -A twitterbot -v "https://unruffled-bassi-05c528.netlify.app/?brand=H%26M&size=S" 2>&1 | grep brand
GET /?brand=H%26M&size=S HTTP/1.1
  <p>Use e.g. the following query parameters: "?brand=H%26M&amp;size=M"</p>
```
`window.location.search: ?brand=H&amp;M&amp;size=S`

Is there an easy solution to this?

**Comment by mrdg** [comment]
I looked into this: the customer is right that this is caused by those `decodeURIComponent` calls in in the prerender code, but we can't remove them without breaking other cases that we're handling there. I did try double encoding the request url so an encoded '&' would stay encoded after decoding but that broke some other test case. I don't know of an easy solution for this.

**Comment by Pieparker** [comment]
Cheers @mrdg, I'll inform the customer that we can see the issue but we're combatting possible regressions. It might be one we want to bring to the wider pod!

**Comment by Pieparker** [comment]
@mrdg, response from the customer:

> Hi! Yeah, I understand that it's a breaking change, but I look at it as a fix of a major bug rather than a change in the behaviour.
> It's quite strange to have the url decoded for you when a bot visits the site, especially when it's done in a destructive manner.

WDYT? If fixing this is a by-and-large improvement, we can create a Community post detailing the change and ask for feedback for a couple of weeks before maybe rolling out a change. Just food for thought!

**Comment by mrdg** [comment]
> @mrdg, response from the customer:
> 
> > Hi! Yeah, I understand that it's a breaking change, but I look at it as a fix of a major bug rather than a change in the behaviour.
> > It's quite strange to have the url decoded for you when a bot visits the site, especially when it's done in a destructive manner.
> 
> WDYT? If fixing this is a by-and-large improvement, we can create a Community post detailing the change and ask for feedback for a couple of weeks before maybe rolling out a change. Just food for thought!

@Pieparker yeah that sounds good, but I'll take another close look today to see if there's a way to fix this without breaking the existing behaviour.

**Comment by mrdg** [comment]
Got a PR out with a fix for this: https://github.com/netlify/prerender/pull/35. I'll try to get it deployed before the end of the week.

**Comment by Pieparker** [comment]
[Customer notified](https://netlify.zendesk.com/agent/tickets/468590). I'll follow up with their response!

**Comment by fool** [comment]
Customer loves it, working better now!

Could we post about it in community updates (cf https://www.notion.so/netlify/How-to-write-about-an-update-or-a-bug-fix-in-Community-8a5ee133467c41bc99b2ab76520e2beb)?  I don't entirely understand the change but perhaps @Pieparker could author and get your signoff?

**Comment by mrdg** [comment]
> Customer loves it, working better now!

:+1:
 
> Could we post about it in community updates (cf https://www.notion.so/netlify/How-to-write-about-an-update-or-a-bug-fix-in-Community-8a5ee133467c41bc99b2ab76520e2beb)? I don't entirely understand the change but perhaps @Pieparker could author and get your signoff?

yes happy to help

**Comment by Pieparker** [comment]
https://community.netlify.com/t/prerendering-prerender-urls-are-no-longer-needlessly-decoded/30830

Ready for review! 🎉

**Comment by mrdg** [comment]
looks good to me!

**Comment by Pieparker** [comment]
Published. Thanks for your help 🙇!
