### ISSUE TITLE
Do not download resources with "prefetch" attribute

### ISSUE THREAD

**Issue by michalhudecek** [netlify/prerender#39]
See the original issue here https://answers.netlify.com/t/pre-rendering-increases-bandwidth-20x/38017

Resources with "prefetch" attribute are not needed for prerendering and are causing huge bandwidth charges.

**Comment by kaganjd** [comment]
Thanks for this @michalhudecek! Linking a related (internal) ticket: https://netlify.zendesk.com/agent/tickets/57409

**Comment by michalhudecek** [comment]
Just an update. Removing prefetch attributes helped which means this issue is behind the huge bandwidth costs. However, the website now feels much slower for the users because the assets cannot be prefetched. This is still a bug in prerendering service that needs to be fixed. **Resources with prefetch attribute should not be downloaded during prerendering.** We just decided for now to deteriorate the user experience in order to save the bandwidth costs.

![image](https://user-images.githubusercontent.com/1215304/122558175-11cb0680-d03e-11eb-906c-49a81340c707.png)

**Comment by michalhudecek** [comment]
Here is a link to a similar issue in original prerender repo: https://github.com/prerender/prerender/pull/629/files

**Comment by flyingjoe** [comment]
Hi @kaganjd, is there any progress on this? This bug blocks us from using Netlify prerendering (more than 5x Bandwidth usage).

**Comment by kaganjd** [comment]
No progress to report, I'm sorry to say. Since this is a blocker for you and I don't have a timeline to share for when we'll make improvements, I'd recommend using Prerender.io and opening a support ticket with us so we can get it configured for you as described here: https://docs.netlify.com/site-deploys/post-processing/prerendering/#external-services
