### ISSUE TITLE
Manually trigger rendering completion

### ISSUE THREAD

**Issue by loganpowell** [netlify/prerender#47]
Hi 👋 

This question is tangentially related [to another issue](https://github.com/netlify/prerender/issues/34), which was resolved. I have a way to tell the prerender when my rendering is complete, rather than relying on [checking at time intervals](https://github.com/netlify/prerender#pagedonechecktimeout). Is there a way to tell the prerender when the page is done loading (e.g., by dispatching an event onto `document`)?

Thank you for listening!

Logan

**Comment by rybit** [comment]
Hello! this repo isn't really the best place to get support. I'd recommend writing into the support team (support@netlify.com) or posting in the forums (https://answers.netlify.com/)!
